//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDDO.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by ndd-gen. DO NOT EDIT.

package v1alpha1

import nddv1 "github.com/yndd/ndd-runtime/apis/common/v1"

// GetActive of this IpamIpam.
func (mg *IpamIpam) GetActive() bool {
	return mg.Spec.Active
}

// GetCondition of this IpamIpam.
func (mg *IpamIpam) GetCondition(ck nddv1.ConditionKind) nddv1.Condition {
	return mg.Status.GetCondition(ck)
}

// GetDeletionPolicy of this IpamIpam.
func (mg *IpamIpam) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this IpamIpam.
func (mg *IpamIpam) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this IpamIpam.
func (mg *IpamIpam) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this IpamIpam.
func (mg *IpamIpam) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this IpamIpam.
func (mg *IpamIpam) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this IpamIpam.
func (mg *IpamIpam) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetConditions of this IpamIpam.
func (mg *IpamIpam) SetConditions(c ...nddv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this IpamIpam.
func (mg *IpamIpam) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this IpamIpam.
func (mg *IpamIpam) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this IpamIpam.
func (mg *IpamIpam) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this IpamIpam.
func (mg *IpamIpam) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this IpamIpam.
func (mg *IpamIpam) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetActive() bool {
	return mg.Spec.Active
}

// GetCondition of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetCondition(ck nddv1.ConditionKind) nddv1.Condition {
	return mg.Status.GetCondition(ck)
}

// GetDeletionPolicy of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetConditions of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetConditions(c ...nddv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this IpamIpamIpaddress.
func (mg *IpamIpamIpaddress) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetActive() bool {
	return mg.Spec.Active
}

// GetCondition of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetCondition(ck nddv1.ConditionKind) nddv1.Condition {
	return mg.Status.GetCondition(ck)
}

// GetDeletionPolicy of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetConditions of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetConditions(c ...nddv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this IpamIpamIpprefix.
func (mg *IpamIpamIpprefix) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetActive() bool {
	return mg.Spec.Active
}

// GetCondition of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetCondition(ck nddv1.ConditionKind) nddv1.Condition {
	return mg.Status.GetCondition(ck)
}

// GetDeletionPolicy of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this IpamIpamIprange.
func (mg *IpamIpamIprange) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetConditions of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetConditions(c ...nddv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this IpamIpamIprange.
func (mg *IpamIpamIprange) SetTarget(t []string) {
	mg.Status.Target = t
}
