//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDDO.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ipam) DeepCopyInto(out *Ipam) {
	*out = *in
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]*IpamAggregate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamAggregate)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Rir != nil {
		in, out := &in.Rir, &out.Rir
		*out = make([]*IpamRir, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamRir)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ipam.
func (in *Ipam) DeepCopy() *Ipam {
	if in == nil {
		return nil
	}
	out := new(Ipam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamAggregate) DeepCopyInto(out *IpamAggregate) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.RirName != nil {
		in, out := &in.RirName, &out.RirName
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamAggregateTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamAggregateTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamAggregate.
func (in *IpamAggregate) DeepCopy() *IpamAggregate {
	if in == nil {
		return nil
	}
	out := new(IpamAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamAggregateTag) DeepCopyInto(out *IpamAggregateTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamAggregateTag.
func (in *IpamAggregateTag) DeepCopy() *IpamAggregateTag {
	if in == nil {
		return nil
	}
	out := new(IpamAggregateTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddress) DeepCopyInto(out *IpamIpaddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DnsName != nil {
		in, out := &in.DnsName, &out.DnsName
		*out = new(string)
		**out = **in
	}
	if in.NatInside != nil {
		in, out := &in.NatInside, &out.NatInside
		*out = new(string)
		**out = **in
	}
	if in.NatOutside != nil {
		in, out := &in.NatOutside, &out.NatOutside
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(string)
		**out = **in
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*IpamIpaddressIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIpaddressIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*IpamIpaddressIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIpaddressIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamIpaddressTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIpaddressTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddress.
func (in *IpamIpaddress) DeepCopy() *IpamIpaddress {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressIpPrefix) DeepCopyInto(out *IpamIpaddressIpPrefix) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressIpPrefix.
func (in *IpamIpaddressIpPrefix) DeepCopy() *IpamIpaddressIpPrefix {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressIpRange) DeepCopyInto(out *IpamIpaddressIpRange) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressIpRange.
func (in *IpamIpaddressIpRange) DeepCopy() *IpamIpaddressIpRange {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressObservation) DeepCopyInto(out *IpamIpaddressObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressObservation.
func (in *IpamIpaddressObservation) DeepCopy() *IpamIpaddressObservation {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressParameters) DeepCopyInto(out *IpamIpaddressParameters) {
	*out = *in
	if in.IpamIpamIpaddress != nil {
		in, out := &in.IpamIpamIpaddress, &out.IpamIpamIpaddress
		*out = new(IpamIpaddress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressParameters.
func (in *IpamIpaddressParameters) DeepCopy() *IpamIpaddressParameters {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressSpec) DeepCopyInto(out *IpamIpaddressSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressSpec.
func (in *IpamIpaddressSpec) DeepCopy() *IpamIpaddressSpec {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressStatus) DeepCopyInto(out *IpamIpaddressStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressStatus.
func (in *IpamIpaddressStatus) DeepCopy() *IpamIpaddressStatus {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpaddressTag) DeepCopyInto(out *IpamIpaddressTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpaddressTag.
func (in *IpamIpaddressTag) DeepCopy() *IpamIpaddressTag {
	if in == nil {
		return nil
	}
	out := new(IpamIpaddressTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpam) DeepCopyInto(out *IpamIpam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpam.
func (in *IpamIpam) DeepCopy() *IpamIpam {
	if in == nil {
		return nil
	}
	out := new(IpamIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamIpaddress) DeepCopyInto(out *IpamIpamIpaddress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamIpaddress.
func (in *IpamIpamIpaddress) DeepCopy() *IpamIpamIpaddress {
	if in == nil {
		return nil
	}
	out := new(IpamIpamIpaddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamIpaddress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamIpaddressList) DeepCopyInto(out *IpamIpamIpaddressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamIpaddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamIpaddressList.
func (in *IpamIpamIpaddressList) DeepCopy() *IpamIpamIpaddressList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamIpaddressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamIpaddressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamIpprefix) DeepCopyInto(out *IpamIpamIpprefix) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamIpprefix.
func (in *IpamIpamIpprefix) DeepCopy() *IpamIpamIpprefix {
	if in == nil {
		return nil
	}
	out := new(IpamIpamIpprefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamIpprefix) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamIpprefixList) DeepCopyInto(out *IpamIpamIpprefixList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamIpprefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamIpprefixList.
func (in *IpamIpamIpprefixList) DeepCopy() *IpamIpamIpprefixList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamIpprefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamIpprefixList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamIprange) DeepCopyInto(out *IpamIpamIprange) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamIprange.
func (in *IpamIpamIprange) DeepCopy() *IpamIpamIprange {
	if in == nil {
		return nil
	}
	out := new(IpamIpamIprange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamIprange) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamIprangeList) DeepCopyInto(out *IpamIpamIprangeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamIprange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamIprangeList.
func (in *IpamIpamIprangeList) DeepCopy() *IpamIpamIprangeList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamIprangeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamIprangeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamList) DeepCopyInto(out *IpamIpamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamList.
func (in *IpamIpamList) DeepCopy() *IpamIpamList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefix) DeepCopyInto(out *IpamIpprefix) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]*IpamIpprefixAggregate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIpprefixAggregate)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(bool)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamIpprefixTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIpprefixTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefix.
func (in *IpamIpprefix) DeepCopy() *IpamIpprefix {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefixAggregate) DeepCopyInto(out *IpamIpprefixAggregate) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefixAggregate.
func (in *IpamIpprefixAggregate) DeepCopy() *IpamIpprefixAggregate {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefixAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefixObservation) DeepCopyInto(out *IpamIpprefixObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefixObservation.
func (in *IpamIpprefixObservation) DeepCopy() *IpamIpprefixObservation {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefixObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefixParameters) DeepCopyInto(out *IpamIpprefixParameters) {
	*out = *in
	if in.IpamIpamIpprefix != nil {
		in, out := &in.IpamIpamIpprefix, &out.IpamIpamIpprefix
		*out = new(IpamIpprefix)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefixParameters.
func (in *IpamIpprefixParameters) DeepCopy() *IpamIpprefixParameters {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefixParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefixSpec) DeepCopyInto(out *IpamIpprefixSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefixSpec.
func (in *IpamIpprefixSpec) DeepCopy() *IpamIpprefixSpec {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefixStatus) DeepCopyInto(out *IpamIpprefixStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefixStatus.
func (in *IpamIpprefixStatus) DeepCopy() *IpamIpprefixStatus {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefixStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpprefixTag) DeepCopyInto(out *IpamIpprefixTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpprefixTag.
func (in *IpamIpprefixTag) DeepCopy() *IpamIpprefixTag {
	if in == nil {
		return nil
	}
	out := new(IpamIpprefixTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprange) DeepCopyInto(out *IpamIprange) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]*IpamIprangeAggregate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIprangeAggregate)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*IpamIprangeIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIprangeIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamIprangeTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamIprangeTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprange.
func (in *IpamIprange) DeepCopy() *IpamIprange {
	if in == nil {
		return nil
	}
	out := new(IpamIprange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeAggregate) DeepCopyInto(out *IpamIprangeAggregate) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeAggregate.
func (in *IpamIprangeAggregate) DeepCopy() *IpamIprangeAggregate {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeIpPrefix) DeepCopyInto(out *IpamIprangeIpPrefix) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeIpPrefix.
func (in *IpamIprangeIpPrefix) DeepCopy() *IpamIprangeIpPrefix {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeObservation) DeepCopyInto(out *IpamIprangeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeObservation.
func (in *IpamIprangeObservation) DeepCopy() *IpamIprangeObservation {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeParameters) DeepCopyInto(out *IpamIprangeParameters) {
	*out = *in
	if in.IpamIpamIprange != nil {
		in, out := &in.IpamIpamIprange, &out.IpamIpamIprange
		*out = new(IpamIprange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeParameters.
func (in *IpamIprangeParameters) DeepCopy() *IpamIprangeParameters {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeSpec) DeepCopyInto(out *IpamIprangeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeSpec.
func (in *IpamIprangeSpec) DeepCopy() *IpamIprangeSpec {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeStatus) DeepCopyInto(out *IpamIprangeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeStatus.
func (in *IpamIprangeStatus) DeepCopy() *IpamIprangeStatus {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIprangeTag) DeepCopyInto(out *IpamIprangeTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIprangeTag.
func (in *IpamIprangeTag) DeepCopy() *IpamIprangeTag {
	if in == nil {
		return nil
	}
	out := new(IpamIprangeTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamObservation) DeepCopyInto(out *IpamObservation) {
	*out = *in
	if in.Nddoipam != nil {
		in, out := &in.Nddoipam, &out.Nddoipam
		*out = new(Nddoipam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamObservation.
func (in *IpamObservation) DeepCopy() *IpamObservation {
	if in == nil {
		return nil
	}
	out := new(IpamObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamParameters) DeepCopyInto(out *IpamParameters) {
	*out = *in
	if in.IpamIpam != nil {
		in, out := &in.IpamIpam, &out.IpamIpam
		*out = new(Ipam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamParameters.
func (in *IpamParameters) DeepCopy() *IpamParameters {
	if in == nil {
		return nil
	}
	out := new(IpamParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamRir) DeepCopyInto(out *IpamRir) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamRirTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamRirTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamRir.
func (in *IpamRir) DeepCopy() *IpamRir {
	if in == nil {
		return nil
	}
	out := new(IpamRir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamRirTag) DeepCopyInto(out *IpamRirTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamRirTag.
func (in *IpamRirTag) DeepCopy() *IpamRirTag {
	if in == nil {
		return nil
	}
	out := new(IpamRirTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamSpec) DeepCopyInto(out *IpamSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamSpec.
func (in *IpamSpec) DeepCopy() *IpamSpec {
	if in == nil {
		return nil
	}
	out := new(IpamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamStatus) DeepCopyInto(out *IpamStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtNetworkNode.DeepCopyInto(&out.AtNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamStatus.
func (in *IpamStatus) DeepCopy() *IpamStatus {
	if in == nil {
		return nil
	}
	out := new(IpamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nddoipam) DeepCopyInto(out *Nddoipam) {
	*out = *in
	if in.Ipam != nil {
		in, out := &in.Ipam, &out.Ipam
		*out = new(NddoipamIpam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nddoipam.
func (in *Nddoipam) DeepCopy() *Nddoipam {
	if in == nil {
		return nil
	}
	out := new(Nddoipam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpam) DeepCopyInto(out *NddoipamIpam) {
	*out = *in
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]*NddoipamIpamAggregate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamAggregate)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpAddress != nil {
		in, out := &in.IpAddress, &out.IpAddress
		*out = make([]*NddoipamIpamIpAddress, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpAddress)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*NddoipamIpamIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Rir != nil {
		in, out := &in.Rir, &out.Rir
		*out = make([]*NddoipamIpamRir, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamRir)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpam.
func (in *NddoipamIpam) DeepCopy() *NddoipamIpam {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamAggregate) DeepCopyInto(out *NddoipamIpamAggregate) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = new(uint32)
		**out = **in
	}
	if in.RirName != nil {
		in, out := &in.RirName, &out.RirName
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamAggregateTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamAggregateTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamAggregate.
func (in *NddoipamIpamAggregate) DeepCopy() *NddoipamIpamAggregate {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamAggregateTag) DeepCopyInto(out *NddoipamIpamAggregateTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamAggregateTag.
func (in *NddoipamIpamAggregateTag) DeepCopy() *NddoipamIpamAggregateTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamAggregateTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpAddress) DeepCopyInto(out *NddoipamIpamIpAddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DnsName != nil {
		in, out := &in.DnsName, &out.DnsName
		*out = new(string)
		**out = **in
	}
	if in.NatInside != nil {
		in, out := &in.NatInside, &out.NatInside
		*out = new(string)
		**out = **in
	}
	if in.NatOutside != nil {
		in, out := &in.NatOutside, &out.NatOutside
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(string)
		**out = **in
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamIpAddressIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpAddressIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*NddoipamIpamIpAddressIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpAddressIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamIpAddressTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpAddressTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpAddress.
func (in *NddoipamIpamIpAddress) DeepCopy() *NddoipamIpamIpAddress {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpAddressIpPrefix) DeepCopyInto(out *NddoipamIpamIpAddressIpPrefix) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpAddressIpPrefix.
func (in *NddoipamIpamIpAddressIpPrefix) DeepCopy() *NddoipamIpamIpAddressIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpAddressIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpAddressIpRange) DeepCopyInto(out *NddoipamIpamIpAddressIpRange) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpAddressIpRange.
func (in *NddoipamIpamIpAddressIpRange) DeepCopy() *NddoipamIpamIpAddressIpRange {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpAddressIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpAddressTag) DeepCopyInto(out *NddoipamIpamIpAddressTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpAddressTag.
func (in *NddoipamIpamIpAddressTag) DeepCopy() *NddoipamIpamIpAddressTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpAddressTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpPrefix) DeepCopyInto(out *NddoipamIpamIpPrefix) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Adresses != nil {
		in, out := &in.Adresses, &out.Adresses
		*out = new(uint32)
		**out = **in
	}
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]*NddoipamIpamIpPrefixAggregate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpPrefixAggregate)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(bool)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamIpPrefixTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpPrefixTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpPrefix.
func (in *NddoipamIpamIpPrefix) DeepCopy() *NddoipamIpamIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpPrefixAggregate) DeepCopyInto(out *NddoipamIpamIpPrefixAggregate) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpPrefixAggregate.
func (in *NddoipamIpamIpPrefixAggregate) DeepCopy() *NddoipamIpamIpPrefixAggregate {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpPrefixAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpPrefixTag) DeepCopyInto(out *NddoipamIpamIpPrefixTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpPrefixTag.
func (in *NddoipamIpamIpPrefixTag) DeepCopy() *NddoipamIpamIpPrefixTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpPrefixTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpRange) DeepCopyInto(out *NddoipamIpamIpRange) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]*NddoipamIpamIpRangeAggregate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpRangeAggregate)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamIpRangeIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpRangeIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(uint32)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamIpRangeTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamIpRangeTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpRange.
func (in *NddoipamIpamIpRange) DeepCopy() *NddoipamIpamIpRange {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpRangeAggregate) DeepCopyInto(out *NddoipamIpamIpRangeAggregate) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpRangeAggregate.
func (in *NddoipamIpamIpRangeAggregate) DeepCopy() *NddoipamIpamIpRangeAggregate {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpRangeAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpRangeIpPrefix) DeepCopyInto(out *NddoipamIpamIpRangeIpPrefix) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpRangeIpPrefix.
func (in *NddoipamIpamIpRangeIpPrefix) DeepCopy() *NddoipamIpamIpRangeIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpRangeIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamIpRangeTag) DeepCopyInto(out *NddoipamIpamIpRangeTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamIpRangeTag.
func (in *NddoipamIpamIpRangeTag) DeepCopy() *NddoipamIpamIpRangeTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamIpRangeTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamRir) DeepCopyInto(out *NddoipamIpamRir) {
	*out = *in
	if in.Aggregates != nil {
		in, out := &in.Aggregates, &out.Aggregates
		*out = new(uint64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamRirTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamRirTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamRir.
func (in *NddoipamIpamRir) DeepCopy() *NddoipamIpamRir {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamRir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamRirTag) DeepCopyInto(out *NddoipamIpamRirTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamRirTag.
func (in *NddoipamIpamRirTag) DeepCopy() *NddoipamIpamRirTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamRirTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Root) DeepCopyInto(out *Root) {
	*out = *in
	if in.IpamNddoipam != nil {
		in, out := &in.IpamNddoipam, &out.IpamNddoipam
		*out = new(Nddoipam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Root.
func (in *Root) DeepCopy() *Root {
	if in == nil {
		return nil
	}
	out := new(Root)
	in.DeepCopyInto(out)
	return out
}
