//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDDO.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ipam) DeepCopyInto(out *Ipam) {
	*out = *in
	if in.Rir != nil {
		in, out := &in.Rir, &out.Rir
		*out = make([]*IpamRir, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamRir)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ipam.
func (in *Ipam) DeepCopy() *Ipam {
	if in == nil {
		return nil
	}
	out := new(Ipam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpam) DeepCopyInto(out *IpamIpam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpam.
func (in *IpamIpam) DeepCopy() *IpamIpam {
	if in == nil {
		return nil
	}
	out := new(IpamIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamList) DeepCopyInto(out *IpamIpamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamList.
func (in *IpamIpamList) DeepCopy() *IpamIpamList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenant) DeepCopyInto(out *IpamIpamTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenant.
func (in *IpamIpamTenant) DeepCopy() *IpamIpamTenant {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantList) DeepCopyInto(out *IpamIpamTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantList.
func (in *IpamIpamTenantList) DeepCopy() *IpamIpamTenantList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstance) DeepCopyInto(out *IpamIpamTenantNetworkinstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstance.
func (in *IpamIpamTenantNetworkinstance) DeepCopy() *IpamIpamTenantNetworkinstance {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceIpaddress) DeepCopyInto(out *IpamIpamTenantNetworkinstanceIpaddress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceIpaddress.
func (in *IpamIpamTenantNetworkinstanceIpaddress) DeepCopy() *IpamIpamTenantNetworkinstanceIpaddress {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceIpaddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceIpaddress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceIpaddressList) DeepCopyInto(out *IpamIpamTenantNetworkinstanceIpaddressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamTenantNetworkinstanceIpaddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceIpaddressList.
func (in *IpamIpamTenantNetworkinstanceIpaddressList) DeepCopy() *IpamIpamTenantNetworkinstanceIpaddressList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceIpaddressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceIpaddressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceIpprefix) DeepCopyInto(out *IpamIpamTenantNetworkinstanceIpprefix) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceIpprefix.
func (in *IpamIpamTenantNetworkinstanceIpprefix) DeepCopy() *IpamIpamTenantNetworkinstanceIpprefix {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceIpprefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceIpprefix) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceIpprefixList) DeepCopyInto(out *IpamIpamTenantNetworkinstanceIpprefixList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamTenantNetworkinstanceIpprefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceIpprefixList.
func (in *IpamIpamTenantNetworkinstanceIpprefixList) DeepCopy() *IpamIpamTenantNetworkinstanceIpprefixList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceIpprefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceIpprefixList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceIprange) DeepCopyInto(out *IpamIpamTenantNetworkinstanceIprange) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceIprange.
func (in *IpamIpamTenantNetworkinstanceIprange) DeepCopy() *IpamIpamTenantNetworkinstanceIprange {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceIprange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceIprange) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceIprangeList) DeepCopyInto(out *IpamIpamTenantNetworkinstanceIprangeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamTenantNetworkinstanceIprange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceIprangeList.
func (in *IpamIpamTenantNetworkinstanceIprangeList) DeepCopy() *IpamIpamTenantNetworkinstanceIprangeList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceIprangeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceIprangeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamTenantNetworkinstanceList) DeepCopyInto(out *IpamIpamTenantNetworkinstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamIpamTenantNetworkinstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamTenantNetworkinstanceList.
func (in *IpamIpamTenantNetworkinstanceList) DeepCopy() *IpamIpamTenantNetworkinstanceList {
	if in == nil {
		return nil
	}
	out := new(IpamIpamTenantNetworkinstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamIpamTenantNetworkinstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamObservation) DeepCopyInto(out *IpamObservation) {
	*out = *in
	if in.Nddoipam != nil {
		in, out := &in.Nddoipam, &out.Nddoipam
		*out = new(Nddoipam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamObservation.
func (in *IpamObservation) DeepCopy() *IpamObservation {
	if in == nil {
		return nil
	}
	out := new(IpamObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamParameters) DeepCopyInto(out *IpamParameters) {
	*out = *in
	if in.IpamIpam != nil {
		in, out := &in.IpamIpam, &out.IpamIpam
		*out = new(Ipam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamParameters.
func (in *IpamParameters) DeepCopy() *IpamParameters {
	if in == nil {
		return nil
	}
	out := new(IpamParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamRir) DeepCopyInto(out *IpamRir) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamRirTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamRirTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamRir.
func (in *IpamRir) DeepCopy() *IpamRir {
	if in == nil {
		return nil
	}
	out := new(IpamRir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamRirTag) DeepCopyInto(out *IpamRirTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamRirTag.
func (in *IpamRirTag) DeepCopy() *IpamRirTag {
	if in == nil {
		return nil
	}
	out := new(IpamRirTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamSpec) DeepCopyInto(out *IpamSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamSpec.
func (in *IpamSpec) DeepCopy() *IpamSpec {
	if in == nil {
		return nil
	}
	out := new(IpamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamStatus) DeepCopyInto(out *IpamStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtNetworkNode.DeepCopyInto(&out.AtNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamStatus.
func (in *IpamStatus) DeepCopy() *IpamStatus {
	if in == nil {
		return nil
	}
	out := new(IpamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenant) DeepCopyInto(out *IpamTenant) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamTenantTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamTenantTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenant.
func (in *IpamTenant) DeepCopy() *IpamTenant {
	if in == nil {
		return nil
	}
	out := new(IpamTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstance) DeepCopyInto(out *IpamTenantNetworkinstance) {
	*out = *in
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamTenantNetworkinstanceTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamTenantNetworkinstanceTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstance.
func (in *IpamTenantNetworkinstance) DeepCopy() *IpamTenantNetworkinstance {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpaddress) DeepCopyInto(out *IpamTenantNetworkinstanceIpaddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DnsName != nil {
		in, out := &in.DnsName, &out.DnsName
		*out = new(string)
		**out = **in
	}
	if in.NatInside != nil {
		in, out := &in.NatInside, &out.NatInside
		*out = new(string)
		**out = **in
	}
	if in.NatOutside != nil {
		in, out := &in.NatOutside, &out.NatOutside
		*out = new(string)
		**out = **in
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamTenantNetworkinstanceIpaddressTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamTenantNetworkinstanceIpaddressTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpaddress.
func (in *IpamTenantNetworkinstanceIpaddress) DeepCopy() *IpamTenantNetworkinstanceIpaddress {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpaddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpaddressObservation) DeepCopyInto(out *IpamTenantNetworkinstanceIpaddressObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpaddressObservation.
func (in *IpamTenantNetworkinstanceIpaddressObservation) DeepCopy() *IpamTenantNetworkinstanceIpaddressObservation {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpaddressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpaddressParameters) DeepCopyInto(out *IpamTenantNetworkinstanceIpaddressParameters) {
	*out = *in
	if in.TenantName != nil {
		in, out := &in.TenantName, &out.TenantName
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.IpamIpamTenantNetworkinstanceIpaddress != nil {
		in, out := &in.IpamIpamTenantNetworkinstanceIpaddress, &out.IpamIpamTenantNetworkinstanceIpaddress
		*out = new(IpamTenantNetworkinstanceIpaddress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpaddressParameters.
func (in *IpamTenantNetworkinstanceIpaddressParameters) DeepCopy() *IpamTenantNetworkinstanceIpaddressParameters {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpaddressParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpaddressSpec) DeepCopyInto(out *IpamTenantNetworkinstanceIpaddressSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpaddressSpec.
func (in *IpamTenantNetworkinstanceIpaddressSpec) DeepCopy() *IpamTenantNetworkinstanceIpaddressSpec {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpaddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpaddressStatus) DeepCopyInto(out *IpamTenantNetworkinstanceIpaddressStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpaddressStatus.
func (in *IpamTenantNetworkinstanceIpaddressStatus) DeepCopy() *IpamTenantNetworkinstanceIpaddressStatus {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpaddressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpaddressTag) DeepCopyInto(out *IpamTenantNetworkinstanceIpaddressTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpaddressTag.
func (in *IpamTenantNetworkinstanceIpaddressTag) DeepCopy() *IpamTenantNetworkinstanceIpaddressTag {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpaddressTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpprefix) DeepCopyInto(out *IpamTenantNetworkinstanceIpprefix) {
	*out = *in
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(bool)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.RirName != nil {
		in, out := &in.RirName, &out.RirName
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamTenantNetworkinstanceIpprefixTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamTenantNetworkinstanceIpprefixTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpprefix.
func (in *IpamTenantNetworkinstanceIpprefix) DeepCopy() *IpamTenantNetworkinstanceIpprefix {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpprefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpprefixObservation) DeepCopyInto(out *IpamTenantNetworkinstanceIpprefixObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpprefixObservation.
func (in *IpamTenantNetworkinstanceIpprefixObservation) DeepCopy() *IpamTenantNetworkinstanceIpprefixObservation {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpprefixObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpprefixParameters) DeepCopyInto(out *IpamTenantNetworkinstanceIpprefixParameters) {
	*out = *in
	if in.TenantName != nil {
		in, out := &in.TenantName, &out.TenantName
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.IpamIpamTenantNetworkinstanceIpprefix != nil {
		in, out := &in.IpamIpamTenantNetworkinstanceIpprefix, &out.IpamIpamTenantNetworkinstanceIpprefix
		*out = new(IpamTenantNetworkinstanceIpprefix)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpprefixParameters.
func (in *IpamTenantNetworkinstanceIpprefixParameters) DeepCopy() *IpamTenantNetworkinstanceIpprefixParameters {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpprefixParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpprefixSpec) DeepCopyInto(out *IpamTenantNetworkinstanceIpprefixSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpprefixSpec.
func (in *IpamTenantNetworkinstanceIpprefixSpec) DeepCopy() *IpamTenantNetworkinstanceIpprefixSpec {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpprefixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpprefixStatus) DeepCopyInto(out *IpamTenantNetworkinstanceIpprefixStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpprefixStatus.
func (in *IpamTenantNetworkinstanceIpprefixStatus) DeepCopy() *IpamTenantNetworkinstanceIpprefixStatus {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpprefixStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIpprefixTag) DeepCopyInto(out *IpamTenantNetworkinstanceIpprefixTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIpprefixTag.
func (in *IpamTenantNetworkinstanceIpprefixTag) DeepCopy() *IpamTenantNetworkinstanceIpprefixTag {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIpprefixTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIprange) DeepCopyInto(out *IpamTenantNetworkinstanceIprange) {
	*out = *in
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*IpamTenantNetworkinstanceIprangeTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IpamTenantNetworkinstanceIprangeTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIprange.
func (in *IpamTenantNetworkinstanceIprange) DeepCopy() *IpamTenantNetworkinstanceIprange {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIprange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIprangeObservation) DeepCopyInto(out *IpamTenantNetworkinstanceIprangeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIprangeObservation.
func (in *IpamTenantNetworkinstanceIprangeObservation) DeepCopy() *IpamTenantNetworkinstanceIprangeObservation {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIprangeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIprangeParameters) DeepCopyInto(out *IpamTenantNetworkinstanceIprangeParameters) {
	*out = *in
	if in.TenantName != nil {
		in, out := &in.TenantName, &out.TenantName
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.IpamIpamTenantNetworkinstanceIprange != nil {
		in, out := &in.IpamIpamTenantNetworkinstanceIprange, &out.IpamIpamTenantNetworkinstanceIprange
		*out = new(IpamTenantNetworkinstanceIprange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIprangeParameters.
func (in *IpamTenantNetworkinstanceIprangeParameters) DeepCopy() *IpamTenantNetworkinstanceIprangeParameters {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIprangeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIprangeSpec) DeepCopyInto(out *IpamTenantNetworkinstanceIprangeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIprangeSpec.
func (in *IpamTenantNetworkinstanceIprangeSpec) DeepCopy() *IpamTenantNetworkinstanceIprangeSpec {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIprangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIprangeStatus) DeepCopyInto(out *IpamTenantNetworkinstanceIprangeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIprangeStatus.
func (in *IpamTenantNetworkinstanceIprangeStatus) DeepCopy() *IpamTenantNetworkinstanceIprangeStatus {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIprangeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceIprangeTag) DeepCopyInto(out *IpamTenantNetworkinstanceIprangeTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceIprangeTag.
func (in *IpamTenantNetworkinstanceIprangeTag) DeepCopy() *IpamTenantNetworkinstanceIprangeTag {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceIprangeTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceObservation) DeepCopyInto(out *IpamTenantNetworkinstanceObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceObservation.
func (in *IpamTenantNetworkinstanceObservation) DeepCopy() *IpamTenantNetworkinstanceObservation {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceParameters) DeepCopyInto(out *IpamTenantNetworkinstanceParameters) {
	*out = *in
	if in.TenantName != nil {
		in, out := &in.TenantName, &out.TenantName
		*out = new(string)
		**out = **in
	}
	if in.IpamIpamTenantNetworkinstance != nil {
		in, out := &in.IpamIpamTenantNetworkinstance, &out.IpamIpamTenantNetworkinstance
		*out = new(IpamTenantNetworkinstance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceParameters.
func (in *IpamTenantNetworkinstanceParameters) DeepCopy() *IpamTenantNetworkinstanceParameters {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceSpec) DeepCopyInto(out *IpamTenantNetworkinstanceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceSpec.
func (in *IpamTenantNetworkinstanceSpec) DeepCopy() *IpamTenantNetworkinstanceSpec {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceStatus) DeepCopyInto(out *IpamTenantNetworkinstanceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceStatus.
func (in *IpamTenantNetworkinstanceStatus) DeepCopy() *IpamTenantNetworkinstanceStatus {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantNetworkinstanceTag) DeepCopyInto(out *IpamTenantNetworkinstanceTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantNetworkinstanceTag.
func (in *IpamTenantNetworkinstanceTag) DeepCopy() *IpamTenantNetworkinstanceTag {
	if in == nil {
		return nil
	}
	out := new(IpamTenantNetworkinstanceTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantObservation) DeepCopyInto(out *IpamTenantObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantObservation.
func (in *IpamTenantObservation) DeepCopy() *IpamTenantObservation {
	if in == nil {
		return nil
	}
	out := new(IpamTenantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantParameters) DeepCopyInto(out *IpamTenantParameters) {
	*out = *in
	if in.IpamIpamTenant != nil {
		in, out := &in.IpamIpamTenant, &out.IpamIpamTenant
		*out = new(IpamTenant)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantParameters.
func (in *IpamTenantParameters) DeepCopy() *IpamTenantParameters {
	if in == nil {
		return nil
	}
	out := new(IpamTenantParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantSpec) DeepCopyInto(out *IpamTenantSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForNetworkNode.DeepCopyInto(&out.ForNetworkNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantSpec.
func (in *IpamTenantSpec) DeepCopy() *IpamTenantSpec {
	if in == nil {
		return nil
	}
	out := new(IpamTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantStatus) DeepCopyInto(out *IpamTenantStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtNetworkNode = in.AtNetworkNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantStatus.
func (in *IpamTenantStatus) DeepCopy() *IpamTenantStatus {
	if in == nil {
		return nil
	}
	out := new(IpamTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamTenantTag) DeepCopyInto(out *IpamTenantTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamTenantTag.
func (in *IpamTenantTag) DeepCopy() *IpamTenantTag {
	if in == nil {
		return nil
	}
	out := new(IpamTenantTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nddoipam) DeepCopyInto(out *Nddoipam) {
	*out = *in
	if in.Ipam != nil {
		in, out := &in.Ipam, &out.Ipam
		*out = new(NddoipamIpam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nddoipam.
func (in *Nddoipam) DeepCopy() *Nddoipam {
	if in == nil {
		return nil
	}
	out := new(Nddoipam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpam) DeepCopyInto(out *NddoipamIpam) {
	*out = *in
	if in.Rir != nil {
		in, out := &in.Rir, &out.Rir
		*out = make([]*NddoipamIpamRir, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamRir)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = make([]*NddoipamIpamTenant, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenant)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpam.
func (in *NddoipamIpam) DeepCopy() *NddoipamIpam {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamRir) DeepCopyInto(out *NddoipamIpamRir) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = new(uint32)
		**out = **in
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamRirTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamRirTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamRir.
func (in *NddoipamIpamRir) DeepCopy() *NddoipamIpamRir {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamRir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamRirTag) DeepCopyInto(out *NddoipamIpamRirTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamRirTag.
func (in *NddoipamIpamRirTag) DeepCopy() *NddoipamIpamRirTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamRirTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenant) DeepCopyInto(out *NddoipamIpamTenant) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = make([]*NddoipamIpamTenantNetworkInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamTenantTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenant.
func (in *NddoipamIpamTenant) DeepCopy() *NddoipamIpamTenant {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstance) DeepCopyInto(out *NddoipamIpamTenantNetworkInstance) {
	*out = *in
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IpAddress != nil {
		in, out := &in.IpAddress, &out.IpAddress
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpAddress, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpAddress)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamTenantNetworkInstanceTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstance.
func (in *NddoipamIpamTenantNetworkInstance) DeepCopy() *NddoipamIpamTenantNetworkInstance {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpAddress) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpAddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DnsName != nil {
		in, out := &in.DnsName, &out.DnsName
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
	if in.NatInside != nil {
		in, out := &in.NatInside, &out.NatInside
		*out = new(string)
		**out = **in
	}
	if in.NatOutside != nil {
		in, out := &in.NatOutside, &out.NatOutside
		*out = new(string)
		**out = **in
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(string)
		**out = **in
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpAddressIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpAddressIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpAddressTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpAddressTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpAddress.
func (in *NddoipamIpamTenantNetworkInstanceIpAddress) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpAddress {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix.
func (in *NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpAddressIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpAddressIpRange) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpAddressIpRange) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpAddressIpRange.
func (in *NddoipamIpamTenantNetworkInstanceIpAddressIpRange) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpAddressIpRange {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpAddressIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpAddressTag) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpAddressTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpAddressTag.
func (in *NddoipamIpamTenantNetworkInstanceIpAddressTag) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpAddressTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpAddressTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefix) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpPrefix) {
	*out = *in
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Adresses != nil {
		in, out := &in.Adresses, &out.Adresses
		*out = new(uint32)
		**out = **in
	}
	if in.Child != nil {
		in, out := &in.Child, &out.Child
		*out = new(NddoipamIpamTenantNetworkInstanceIpPrefixChild)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(NddoipamIpamTenantNetworkInstanceIpPrefixParent)
		(*in).DeepCopyInto(*out)
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(bool)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.RirName != nil {
		in, out := &in.RirName, &out.RirName
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpPrefixTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpPrefixTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpPrefix.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefix) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixChild) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpPrefixChild) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpPrefixChild.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixChild) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpPrefixChild {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpPrefixChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpPrefixChildIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixParent) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpPrefixParent) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpPrefixParent.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixParent) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpPrefixParent {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpPrefixParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpPrefixParentIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixTag) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpPrefixTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpPrefixTag.
func (in *NddoipamIpamTenantNetworkInstanceIpPrefixTag) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpPrefixTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpPrefixTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpRange) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpRange) {
	*out = *in
	if in.AddressAllocationStrategy != nil {
		in, out := &in.AddressAllocationStrategy, &out.AddressAllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(NddoipamIpamTenantNetworkInstanceIpRangeParent)
		(*in).DeepCopyInto(*out)
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(uint32)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpRangeTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpRangeTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpRange.
func (in *NddoipamIpamTenantNetworkInstanceIpRange) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpRange {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpRangeParent) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpRangeParent) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpRangeParent.
func (in *NddoipamIpamTenantNetworkInstanceIpRangeParent) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpRangeParent {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpRangeParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix.
func (in *NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpRangeParentIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceIpRangeTag) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceIpRangeTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceIpRangeTag.
func (in *NddoipamIpamTenantNetworkInstanceIpRangeTag) DeepCopy() *NddoipamIpamTenantNetworkInstanceIpRangeTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceIpRangeTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantNetworkInstanceTag) DeepCopyInto(out *NddoipamIpamTenantNetworkInstanceTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantNetworkInstanceTag.
func (in *NddoipamIpamTenantNetworkInstanceTag) DeepCopy() *NddoipamIpamTenantNetworkInstanceTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantNetworkInstanceTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoipamIpamTenantTag) DeepCopyInto(out *NddoipamIpamTenantTag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoipamIpamTenantTag.
func (in *NddoipamIpamTenantTag) DeepCopy() *NddoipamIpamTenantTag {
	if in == nil {
		return nil
	}
	out := new(NddoipamIpamTenantTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Root) DeepCopyInto(out *Root) {
	*out = *in
	if in.IpamNddoipam != nil {
		in, out := &in.IpamNddoipam, &out.IpamNddoipam
		*out = new(Nddoipam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Root.
func (in *Root) DeepCopy() *Root {
	if in == nil {
		return nil
	}
	out := new(Root)
	in.DeepCopyInto(out)
	return out
}
